# Generated by Django 6.0.6 on 2026-07-01 01:02

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChargeRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('free_minutes', models.IntegerField(default=15, verbose_name='免费时长（分钟）')),
                ('first_hour_fee', models.DecimalField(decimal_places=2, default=5.0, max_digits=10, verbose_name='首小时收费')),
                ('hourly_rate', models.DecimalField(decimal_places=2, default=2.0, max_digits=10, verbose_name='超时单价（每小时）')),
                ('daily_max', models.DecimalField(decimal_places=2, default=30.0, max_digits=10, verbose_name='日封顶价格')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用状态')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '收费规则',
                'verbose_name_plural': '收费规则',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('phone', models.CharField(blank=True, max_length=11, verbose_name='手机号')),
                ('role', models.CharField(choices=[('user', '普通用户'), ('admin', '管理员')], default='user', max_length=10, verbose_name='角色')),
                ('status', models.BooleanField(default=True, verbose_name='账号状态')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate_number', models.CharField(max_length=20, unique=True, verbose_name='车牌号')),
                ('car_type', models.CharField(choices=[('small', '小型车'), ('suv', 'SUV'), ('large', '大型车')], default='small', max_length=10, verbose_name='车辆类型')),
                ('is_bound_fixed', models.BooleanField(default=False, verbose_name='是否绑定固定车位')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars', to=settings.AUTH_USER_MODEL, verbose_name='所有者')),
            ],
            options={
                'verbose_name': '车辆',
                'verbose_name_plural': '车辆',
            },
        ),
        migrations.CreateModel(
            name='ParkingSpace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('space_no', models.CharField(max_length=20, unique=True, verbose_name='车位编号')),
                ('space_type', models.CharField(choices=[('fixed', '固定车位'), ('temporary', '临时车位')], default='temporary', max_length=10, verbose_name='车位类型')),
                ('status', models.CharField(choices=[('free', '空闲'), ('occupied', '已占用'), ('locked', '已锁定')], default='free', max_length=10, verbose_name='车位状态')),
                ('zone', models.CharField(blank=True, max_length=50, verbose_name='所属区域')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('bound_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='绑定用户')),
            ],
            options={
                'verbose_name': '车位',
                'verbose_name_plural': '车位',
            },
        ),
        migrations.CreateModel(
            name='ParkingRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate_number', models.CharField(max_length=20, verbose_name='车牌号')),
                ('entry_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='进场时间')),
                ('exit_time', models.DateTimeField(blank=True, null=True, verbose_name='离场时间')),
                ('duration_minutes', models.IntegerField(default=0, verbose_name='停车时长（分钟）')),
                ('fee', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='费用金额')),
                ('pay_status', models.CharField(choices=[('unpaid', '未结算'), ('paid', '已结算'), ('cancelled', '已取消')], default='unpaid', max_length=10, verbose_name='缴费状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('car', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='parking.car', verbose_name='关联车辆')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
                ('space', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='parking.parkingspace', verbose_name='车位')),
            ],
            options={
                'verbose_name': '停车记录',
                'verbose_name_plural': '停车记录',
                'ordering': ['-entry_time'],
            },
        ),
        migrations.AddField(
            model_name='car',
            name='bound_space',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='parking.parkingspace', verbose_name='绑定车位'),
        ),
    ]
